### ISSUE TITLE
Assistants V2

### ISSUE THREAD

**Issue by phact** [datastax/astra-assistants-api#22]
https://platform.openai.com/docs/assistants/whats-new

```[tasklist]
### Tasks
- [x] Vector Stores
- [x] Vector Store Files
- [x] Vector Store Objects
- [x] file_search tool
- [x] assistants_v2
- [x] messages_v2
- [x] threads_v2
- [x] runs_v2
- [x] non streaming tests (threads, run, retreival, function calling)
- [x] streaming tests (threads, run, retreival, function calling)
```

**Comment by phact** [comment]
Related https://github.com/phact/streaming-assistants/issues/2

**Comment by phact** [comment]
merged https://github.com/datastax/astra-assistants-api/pull/35
